# GitHub Native Sponsorship (requires setting up a GitHub Sponsors profile)
github: windraman


# Direct Web Links (Perfect for PayPal, Saweria, etc.)
custom: ['https://paypal.me/Wahyu.Akman', 'https://saweria.co/windraman']
